# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180116_1758'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='series_set',
            field=models.ManyToManyField(blank=True, null=True, related_name='series_set', to='series.Series'),
        ),
    ]
