# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180116_1758'),
        ('profiles', '0002_profile_series_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='series_set',
        ),
        migrations.AddField(
            model_name='profile',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='series', to='series.Series'),
        ),
    ]
