# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180120_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='series',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='series.Series'),
        ),
    ]
