# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180116_1758'),
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='serie',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
    ]
