# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_episode_serie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['auto_id']},
        ),
        migrations.RemoveField(
            model_name='episode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='number',
        ),
        migrations.AddField(
            model_name='episode',
            name='auto_id',
            field=models.IntegerField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
