# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_auto_20180116_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='auto_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
