# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0004_auto_20180117_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='auto_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
