# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0006_episode_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='title',
        ),
    ]
