# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0007_auto_20180117_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='serie',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='auto_id',
        ),
        migrations.AddField(
            model_name='episode',
            name='ep_number',
            field=models.IntegerField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
