# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0008_auto_20180119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='ep_number',
            field=models.IntegerField(editable=False),
        ),
    ]
