# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
