# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_series_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='title',
        ),
    ]
