# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180116_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='released',
            field=models.DateField(null=True),
        ),
    ]
