# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_series_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='rel',
        ),
    ]
